/**
 * v2.0 — Java enum -> TS enum aggregated emitter.
 *
 * Takes every JavaFile classified as `java-enum`, parses each, and emits
 * a single `types/enums.ts` with `export enum X { ... }` blocks plus
 * TODO comments capturing any enum-method bodies the user may need to
 * port by hand (Java enums can carry instance methods + static helpers;
 * TS enums cannot).
 *
 * Only fires when ConvertOptions.layout === "v2-organized". v1-flat keeps
 * the current behaviour where enums fall through to customUtilDetector and
 * land as stubs in tests/_legacy-stubs/.
 *
 * Patterns handled:
 *   - Value-bearing enums:   `SINGLE("Single"), FAMILY("Family")` → `SINGLE = "Single"`
 *   - Plain constant enums:  `LOCAL, REMOTE`                       → `LOCAL = "LOCAL"`
 *   - Multiline declarations: the whole declarations list (between `{`
 *     and the first `;`) is treated as one block, split on top-level commas
 *     that aren't inside parentheses.
 *
 * Patterns NOT handled (surfaced as TODO comments inside the emitted file):
 *   - Enum instance methods (e.g. RoomType.get() in eliasnogueira's example)
 *   - Static initializer blocks
 *   - Enum types implementing functional interfaces
 */

import { JavaFile, ReviewItem } from "../types";

export interface EnumEmitterOutput {
  /** Full TS source for types/enums.ts (empty string if no enums to emit). */
  source: string;
  /** Review items — one INFO per enum, plus MANUAL items for skipped method bodies. */
  warnings: ReviewItem[];
}

export function emitEnumsFile(files: JavaFile[]): EnumEmitterOutput {
  const enumFiles = files.filter((f) => f.kind === "java-enum");
  if (enumFiles.length === 0) {
    return { source: "", warnings: [] };
  }

  const blocks: string[] = [];
  const warnings: ReviewItem[] = [];

  blocks.push(
    "// Generated by sel2pw (--layout v2-organized) — aggregated Java enums.",
    "// Each `export enum` block came from a Java enum source file.",
    "// If the original enum had instance methods or static helpers, they",
    "// were NOT translated (TS enums don't support either); see the TODO",
    "// comments next to each block for the manual-port hint.",
    "",
  );

  for (const file of enumFiles) {
    const parsed = parseEnum(file.source, file.className);
    blocks.push(renderEnum(parsed));
    blocks.push("");

    if (parsed.skippedMethods.length > 0) {
      warnings.push({
        file: file.path,
        severity: "manual",
        message:
          `Enum \`${file.className}\` had ${parsed.skippedMethods.length} ` +
          `instance method(s)/initializer(s) that TS enums cannot express ` +
          `(${parsed.skippedMethods.join(", ")}). Port them as standalone ` +
          `helper functions next to the enum in types/enums.ts.`,
      });
    }

    warnings.push({
      file: file.path,
      severity: "info",
      message: `Converted \`${file.className}\` to TS enum at types/enums.ts.`,
    });
  }

  return { source: blocks.join("\n"), warnings };
}

// ---------- internals ---------------------------------------------------

interface ParsedEnum {
  name: string;
  /** [memberName, valueLiteral] pairs. valueLiteral is a TS string/number literal. */
  members: Array<{ name: string; value: string }>;
  /** Names of instance methods or static blocks we skipped. */
  skippedMethods: string[];
}

function parseEnum(source: string, fallbackName: string): ParsedEnum {
  // Strip block + line comments so they don't confuse the body scan.
  const stripped = source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "");

  // Find the enum name.
  const nameRe =
    /\b(?:public\s+|protected\s+|private\s+)?enum\s+(\w+)\b/m;
  const nameMatch = stripped.match(nameRe);
  const name = nameMatch ? nameMatch[1] : fallbackName;

  // The declarations list lives between the enum's opening `{` and the
  // first top-level `;` (which separates declarations from method bodies).
  // If there's no semicolon, the whole body is just declarations.
  const bodyStart = stripped.indexOf("{", nameMatch?.index ?? 0);
  if (bodyStart === -1) {
    return { name, members: [], skippedMethods: [] };
  }
  const body = stripped.slice(bodyStart + 1);

  // Top-level semicolon ends the declarations list. We need to ignore semis
  // inside parens (rare in declarations but possible in argument lists).
  let depth = 0;
  let declEnd = body.length;
  for (let i = 0; i < body.length; i++) {
    const ch = body[i];
    if (ch === "(" || ch === "{" || ch === "[") depth++;
    else if (ch === ")" || ch === "}" || ch === "]") depth--;
    else if (ch === ";" && depth === 0) {
      declEnd = i;
      break;
    }
  }
  const decls = body.slice(0, declEnd).trim();
  const rest = body.slice(declEnd + 1);

  // Split decls on top-level commas (respect parens for `NAME("v", "w")`).
  const members: Array<{ name: string; value: string }> = [];
  let cur = "";
  let parenDepth = 0;
  for (let i = 0; i < decls.length; i++) {
    const ch = decls[i];
    if (ch === "(") parenDepth++;
    else if (ch === ")") parenDepth--;
    if (ch === "," && parenDepth === 0) {
      const m = parseMember(cur);
      if (m) members.push(m);
      cur = "";
    } else {
      cur += ch;
    }
  }
  if (cur.trim()) {
    const m = parseMember(cur);
    if (m) members.push(m);
  }

  // Surface any method-like signatures in the rest section so the user
  // sees them in the review report.
  const skippedMethods: string[] = [];
  const methodRe =
    /\b(?:public|private|protected|static)?\s+(?:[\w<>,.\s[\]]+\s+)?(\w+)\s*\([^)]*\)\s*\{/g;
  let mm: RegExpExecArray | null;
  while ((mm = methodRe.exec(rest)) !== null) {
    const methodName = mm[1];
    if (
      methodName !== "if" &&
      methodName !== "for" &&
      methodName !== "while" &&
      methodName !== "switch" &&
      methodName !== name
    ) {
      skippedMethods.push(methodName);
    }
  }
  // Also catch static initialiser blocks.
  if (/\bstatic\s*\{/.test(rest)) skippedMethods.push("(static initializer)");

  return { name, members, skippedMethods };
}

function parseMember(
  raw: string,
): { name: string; value: string } | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;

  // Value-bearing: NAME("literal", ...) — first string literal becomes the
  // TS enum value. If the constructor takes a non-string first arg (number,
  // boolean), use the raw expression as the value.
  const callMatch = trimmed.match(/^([A-Z][A-Z0-9_]*)\s*\(([^]*)\)\s*$/);
  if (callMatch) {
    const ident = callMatch[1];
    const args = callMatch[2].trim();
    if (args.length === 0) {
      // Empty parens — treat as plain constant.
      return { name: ident, value: `"${ident}"` };
    }
    // Find the first top-level argument.
    let depth = 0;
    let firstArg = "";
    for (let i = 0; i < args.length; i++) {
      const ch = args[i];
      if (ch === "(" || ch === "[" || ch === "{") depth++;
      else if (ch === ")" || ch === "]" || ch === "}") depth--;
      else if (ch === "," && depth === 0) break;
      firstArg += ch;
    }
    firstArg = firstArg.trim();
    return { name: ident, value: firstArg };
  }

  // Plain constant: bare identifier, no parens.
  const bareMatch = trimmed.match(/^([A-Z][A-Z0-9_]*)\s*$/);
  if (bareMatch) {
    const ident = bareMatch[1];
    return { name: ident, value: `"${ident}"` };
  }

  return null;
}

function renderEnum(p: ParsedEnum): string {
  const lines: string[] = [];
  if (p.skippedMethods.length > 0) {
    lines.push(
      `// TODO(sel2pw): the Java enum \`${p.name}\` had additional methods/initializers ` +
      `that TS enums can't express: ${p.skippedMethods.join(", ")}. ` +
      `Port them as standalone helper functions if needed.`,
    );
  }
  lines.push(`export enum ${p.name} {`);
  for (const m of p.members) {
    lines.push(`  ${m.name} = ${m.value},`);
  }
  lines.push("}");
  return lines.join("\n");
}
