/**
 * v2.0 — Java exception class -> TS error class aggregated emitter.
 *
 * Takes every JavaFile classified as `java-exception`, parses each, and
 * emits a single `types/errors.ts` with `export class FooException extends
 * Error { ... }` blocks.
 *
 * Conversion rules:
 *   - Java `extends *Exception | *Error | Throwable` becomes `extends Error`
 *     (TS has a single Error base — sub-typing IllegalStateException etc.
 *     adds no runtime value).
 *   - Constructors are translated by parameter signature; the body is best-
 *     effort: `super(String.format("foo %s", x))` becomes
 *     ``super(`foo ${x}`)`` so the user sees the same message at runtime.
 *   - `this.name = 'FooException'` is added automatically so stack traces
 *     and instanceof checks behave like the original Java naming.
 *
 * Only fires when ConvertOptions.layout === "v2-organized". v1-flat keeps
 * the current behaviour where exceptions fall through to customUtilDetector
 * and land as stubs in tests/_legacy-stubs/.
 */

import { JavaFile, ReviewItem } from "../types";

export interface ErrorEmitterOutput {
  /** Full TS source for types/errors.ts (empty string if no exceptions). */
  source: string;
  warnings: ReviewItem[];
}

export function emitErrorsFile(files: JavaFile[]): ErrorEmitterOutput {
  const errFiles = files.filter((f) => f.kind === "java-exception");
  if (errFiles.length === 0) {
    return { source: "", warnings: [] };
  }

  const blocks: string[] = [];
  const warnings: ReviewItem[] = [];

  blocks.push(
    "// Generated by sel2pw (--layout v2-organized) — aggregated Java exceptions.",
    "// Each `export class` block came from a Java exception source file.",
    "// All Java exception hierarchies collapse to `extends Error` in TS.",
    "",
  );

  for (const file of errFiles) {
    const parsed = parseException(file.source, file.className);
    blocks.push(renderException(parsed));
    blocks.push("");

    warnings.push({
      file: file.path,
      severity: "info",
      message: `Converted \`${file.className}\` to TS error class at types/errors.ts.`,
    });
  }

  return { source: blocks.join("\n"), warnings };
}

// ---------- internals ---------------------------------------------------

interface ParsedException {
  name: string;
  /** Constructors found in the original Java source. */
  constructors: Array<{ params: string[]; bodyExpr: string }>;
}

function parseException(source: string, fallbackName: string): ParsedException {
  // Strip comments before scanning so doc strings don't confuse the regexes.
  const stripped = source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "");

  const nameRe =
    /\bpublic\s+(?:abstract\s+|final\s+)?class\s+(\w+)\s+extends\s+\w*(?:Exception|Error|Throwable)\b/m;
  const nameMatch = stripped.match(nameRe);
  const name = nameMatch ? nameMatch[1] : fallbackName;

  // Find all constructors: `public ClassName(...) { ... }`.
  const ctorRe = new RegExp(
    `\\bpublic\\s+${escapeRegex(name)}\\s*\\(([^)]*)\\)\\s*\\{([\\s\\S]*?)\\n\\s*\\}`,
    "g",
  );
  const constructors: ParsedException["constructors"] = [];
  let m: RegExpExecArray | null;
  while ((m = ctorRe.exec(stripped)) !== null) {
    const paramRaw = m[1].trim();
    const body = m[2].trim();
    const params: string[] = [];
    if (paramRaw.length > 0) {
      for (const p of paramRaw.split(",")) {
        const t = p.trim();
        if (!t) continue;
        // Last token is the name; rest is the Java type. We only need the name.
        const parts = t.split(/\s+/);
        const paramName = parts[parts.length - 1];
        params.push(paramName);
      }
    }
    constructors.push({ params, bodyExpr: convertSuperCall(body) });
  }

  // If no explicit constructor, synthesise a `constructor(message?: string)` form.
  if (constructors.length === 0) {
    constructors.push({
      params: [],
      bodyExpr: "super();",
    });
  }

  return { name, constructors };
}

function renderException(p: ParsedException): string {
  const lines: string[] = [];
  lines.push(`export class ${p.name} extends Error {`);
  for (const ctor of p.constructors) {
    const paramSig =
      ctor.params.length > 0
        ? ctor.params.map((n) => `${n}: string`).join(", ")
        : "message?: string";
    lines.push(`  constructor(${paramSig}) {`);
    // If we synthesised the default `super();`, use the parameter instead.
    if (ctor.bodyExpr === "super();") {
      lines.push("    super(message);");
    } else {
      lines.push(`    ${ctor.bodyExpr}`);
    }
    lines.push(`    this.name = "${p.name}";`);
    lines.push("  }");
  }
  lines.push("}");
  return lines.join("\n");
}

/**
 * Translate the Java exception ctor body's `super(...)` call into the
 * equivalent TS template-literal call. Best-effort: only the first
 * statement is processed; any additional bookkeeping is dropped (TS error
 * classes are simple — there's nothing to bookkeep in most projects).
 *
 * Uses a paren-balancing scan instead of a regex so calls like
 * `super(String.format("...", arg))` get their FULL argument expression
 * extracted (a naive [^)]* match stops at the inner `)`).
 */
function convertSuperCall(javaBody: string): string {
  const superIdx = javaBody.search(/\bsuper\s*\(/);
  if (superIdx === -1) return "super();";
  // Move to the `(` that opens the call.
  const openParen = javaBody.indexOf("(", superIdx);
  if (openParen === -1) return "super();";
  let depth = 1;
  let close = openParen + 1;
  while (close < javaBody.length && depth > 0) {
    const ch = javaBody[close];
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    if (depth === 0) break;
    close++;
  }
  if (depth !== 0) return "super();";
  const argRaw = javaBody.slice(openParen + 1, close).trim();
  if (!argRaw) return "super();";

  // String.format("…%s…", arg) → template literal `…${arg}…`.
  const fmtMatch = argRaw.match(
    /^String\.format\s*\(\s*"([^"]*)"\s*,\s*([^)]+)\)$/,
  );
  if (fmtMatch) {
    const tmpl = fmtMatch[1];
    const rest = fmtMatch[2].trim();
    const args = splitArgs(rest);
    let out = "";
    let argIdx = 0;
    let i = 0;
    while (i < tmpl.length) {
      if (tmpl[i] === "%" && i + 1 < tmpl.length) {
        out += "${" + (args[argIdx++] ?? "?") + "}";
        i += 2;
      } else {
        out += tmpl[i];
        i++;
      }
    }
    return "super(`" + out + "`);";
  }

  return `super(${argRaw});`;
}

function splitArgs(raw: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let cur = "";
  for (let i = 0; i < raw.length; i++) {
    const ch = raw[i];
    if (ch === "(" || ch === "[" || ch === "{") depth++;
    else if (ch === ")" || ch === "]" || ch === "}") depth--;
    else if (ch === "," && depth === 0) {
      out.push(cur.trim());
      cur = "";
      continue;
    }
    cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
