/**
 * Detect a "log in once, save state" pattern across converted Page Objects
 * + tests, and emit `tests/auth.setup.ts` (Playwright's [storageState] setup
 * file convention) so subsequent specs reuse the saved login state.
 *
 * Heuristic: if there's a Page Object whose class name matches /Login/i
 * with a `login(username, password)` method, AND the user opted into auth
 * setup via `emit_auth_setup: true`, generate:
 *
 *   tests/auth.setup.ts:
 *     import { test as setup } from '@playwright/test';
 *     import { LoginPage } from '../pages/login.page';
 *     setup('authenticate', async ({ page }) => {
 *       const login = new LoginPage(page);
 *       await login.open(process.env.BASE_URL ?? '');
 *       await login.login(process.env.TEST_USER ?? '', process.env.TEST_PASSWORD ?? '');
 *       await page.context().storageState({ path: 'playwright/.auth/user.json' });
 *     });
 */

import { ConvertedFile, PageObjectIR } from "../types";

export function detectAndEmitAuthSetup(
  pageObjectIRs: PageObjectIR[],
): ConvertedFile | null {
  const loginPage = pageObjectIRs.find(
    (p) => /login/i.test(p.className) && p.methods.some((m) => m.name === "login"),
  );
  if (!loginPage) return null;
  const importPath =
    "../pages/" +
    loginPage.className
      .replace(/Page$/, "")
      .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
      .toLowerCase() +
    ".page";

  const lines: string[] = [];
  lines.push(`import { test as setup } from '@playwright/test';`);
  lines.push(`import { ${loginPage.className} } from '${importPath}';`);
  lines.push("");
  lines.push(`/**`);
  lines.push(
    ` * Auto-generated by sel2pw. Run before the test suite to persist auth state:`,
  );
  lines.push(
    ` *   playwright.config.ts → projects: [{ name:'setup', testMatch:/.*\\.setup\\.ts/ }]`,
  );
  lines.push(` */`);
  lines.push(`setup('authenticate', async ({ page }) => {`);
  lines.push(`  const login = new ${loginPage.className}(page);`);
  lines.push(`  await login.open(process.env.BASE_URL ?? '');`);
  lines.push(
    `  await login.login(process.env.TEST_USER ?? '', process.env.TEST_PASSWORD ?? '');`,
  );
  lines.push(
    `  await page.context().storageState({ path: 'playwright/.auth/user.json' });`,
  );
  lines.push(`});`);
  lines.push("");

  return {
    relPath: "tests/auth.setup.ts",
    source: lines.join("\n"),
    warnings: [],
    kind: "test",
  };
}
